source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'CodeClimateExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CodeClimateExample
  target 'CodeClimateExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CodeClimateExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
